/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type Route = {
  _id: string;
  _type: "route";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  slug?: Slug;
  page?: PageReference;
  includeInSitemap?: boolean;
  disallowRobots?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type TextSection = {
  _type: "textSection";
  label?: string;
  heading?: string;
  text?: PortableText;
};

export type SimplePortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<
        | ({
            _key: string;
          } & Link)
        | ({
            _key: string;
          } & InternalLink)
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & EmbedHTML)
>;

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | ({
            _key: string;
          } & Link)
        | ({
            _key: string;
          } & InternalLink)
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & Figure)
  | ({
      _key: string;
    } & EmbedHTML)
>;

export type MatchReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "match";
};

export type Round = {
  _type: "round";
  hasType?: "quaterFinal" | "semiFinal" | "bronzeFinal" | "final";
  games?: Array<
    {
      _key: string;
    } & MatchReference
  >;
};

export type PlayerReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "player";
};

export type PlayerResult = {
  _type: "playerResult";
  player?: PlayerReference;
  isWinner?: boolean;
  score?: Array<number>;
};

export type Link = {
  _type: "link";
  href?: string;
};

export type RouteReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "route";
};

export type InternalLink = PageReference | RouteReference;

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Figure = {
  _type: "figure";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
};

export type EmbedHTML = {
  _type: "embedHTML";
  html?: string;
};

export type SiteConfig = {
  _id: string;
  _type: "siteConfig";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  url?: string;
  frontpage?: PageReference;
  lang?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  mainNavigation?: Array<
    {
      _key: string;
    } & RouteReference
  >;
  footerNavigation?: Array<
    {
      _key: string;
    } & RouteReference
  >;
  footerText?: SimplePortableText;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Player = {
  _id: string;
  _type: "player";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  mainRepresentation?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  content?: Array<
    {
      _key: string;
    } & TextSection
  >;
  description?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type CupReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cup";
};

export type Tournament = {
  _id: string;
  _type: "tournament";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  start?: string;
  end?: string;
  games?: Array<MatchReference | CupReference>;
  mainRepresentation?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: string;
};

export type TournamentReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tournament";
};

export type Cup = {
  _id: string;
  _type: "cup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  start?: string;
  end?: string;
  rounds?: Array<
    {
      _key: string;
    } & Round
  >;
  mainRepresentation?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  partOf?: Array<
    {
      _key: string;
    } & TournamentReference
  >;
  description?: string;
};

export type Match = {
  _id: string;
  _type: "match";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  gameStart?: string;
  results?: Array<
    {
      _key: string;
    } & PlayerResult
  >;
  mainRepresentation?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  partOf?: Array<
    {
      _key: string;
    } & TournamentReference
  >;
  description?: string;
};

export type MediaTag = {
  _id: string;
  _type: "media.tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: Slug;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | PageReference
  | Route
  | Slug
  | TextSection
  | SimplePortableText
  | PortableText
  | MatchReference
  | Round
  | PlayerReference
  | PlayerResult
  | Link
  | RouteReference
  | InternalLink
  | SanityImageAssetReference
  | Figure
  | EmbedHTML
  | SiteConfig
  | SanityImageCrop
  | SanityImageHotspot
  | Player
  | Page
  | CupReference
  | Tournament
  | TournamentReference
  | Cup
  | Match
  | MediaTag
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;
